language: node_js
node_js:
  - "0.10"

script:
  - npm install
  - ./node_modules/.bin/gulp ci

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./node_modules/.bin/gulp  --ghPagesRemoteUrl "$ghPagesRemoteUrl" ; fi