sudo: required
dist: trusty

addons:
  apt:
    packages:
      - dbus-x11
      - xpra

language: node_js

node_js:
  - 7

os:
  - linux

env:
  global:
    - DISPLAY=:99

before_install:
  - xpra start :99
  - npm install -g npm@latest

script:
  - dbus-launch --exit-with-session npm run ci
