addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - xpra

language: node_js

node_js:
  - 5

os:
  - linux

env:
  global:
    - CC=gcc-5 CXX=g++-5 DISPLAY=:99

before_install:
  - xpra start :99
  - npm install -g npm@latest
  - npm config set progress false

script:
  - ./node_modules/.bin/gulp ci

after_success:
  - git config --global user.email "$gitUserEmail"
  - git config --global user.name "$gitUserName"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "zaklinaczekodu/human-library" ]; then ./node_modules/.bin/gulp deployGhPages --ghPagesRemoteUrl "$ghPagesRemoteUrl" ; fi