sudo: required
dist: trusty

addons:
  apt:
    packages:
      - dbus-x11
      - xpra

language: node_js

node_js:
  - 6

os:
  - linux

env:
  global:
    - DISPLAY=:99

before_install:
  - xpra start :99
  - npm install -g npm@latest

script:
  - dbus-launch --exit-with-session ./node_modules/.bin/gulp ci

after_success:
  - git config --global user.email "$gitUserEmail"
  - git config --global user.name "$gitUserName"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "zaklinaczekodu/human-library" ]; then ./node_modules/.bin/gulp deployGhPages --ghPagesRemoteUrl "$ghPagesRemoteUrl" ; fi