sudo: required
dist: trusty

addons:
  apt:
    packages:
      - dbus-x11
      - xpra

language: node_js

node_js:
  - 7

os:
  - linux

env:
  global:
    - DISPLAY=:99

before_install:
  - xpra start :99
  - npm install -g npm@latest

script:
  - dbus-launch --exit-with-session ./node_modules/.bin/gulp ci

after_success:
  - git config --global user.email "$HLTRAVIS_GIT_MAIL"
  - git config --global user.name "$HLTRAVIS_GIT_NAME"
  - >
    if
      [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
      [ ! -z "$TRAVIS_TAG" ] &&
      [ "$TRAVIS_REPO_SLUG" == "humanlibrary/humanlibrary" ];
    then
      echo "services.humanlibrary.org" > dist/CNAME
      ./node_modules/.bin/gulp deployGhPages --ghPagesRemoteUrl "$HLTRAVIS_GIT_PRODUCTION_URL" ;
    fi