name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: docker compose up npm-install --exit-code-from=npm-install
      - name: build
        run: docker compose up build --exit-code-from=build
      - name: test
        run: docker compose up test --exit-code-from=test
